version: '3.7'

services:
  mensa-api-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: build-stage
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: mensa-api-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
